import { ProductItem, ListingItem, OrderEconomics, MonthlyDataPoint, StoreInfo } from '@/types';
import { DEFAULT_SETTINGS } from './calculations';

// ----------------------------------------------------
// STORE 1: My TikTok Shop (Tech & Gadgets - US)
// ----------------------------------------------------
export const STORE_1_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'Wireless Charger 15W',
    sku: 'WC-001',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=300&auto=format&fit=crop&q=80',
    costPrice: 9.00,
    shippingCost: 2.00,
    packagingCost: 1.00,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 3.50,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 29.99,
    createdAt: '2024-05-18',
    updatedAt: '2024-05-18',
    status: 'excellent',
    bestFor: 'Overall Winner 🏆',
    notes: 'Top performing hero product with viral video conversion.',
    inComparison: true,
  },
  {
    id: 'prod-2',
    name: 'Smart Fitness Watch',
    sku: 'SW-104',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&auto=format&fit=crop&q=80',
    costPrice: 18.00,
    shippingCost: 2.50,
    packagingCost: 1.00,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 5.00,
    creatorCost: 0.50,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 49.99,
    createdAt: '2024-05-16',
    updatedAt: '2024-05-16',
    status: 'good',
    bestFor: 'High Revenue',
    notes: 'Strong margins, stable supply chain.',
    inComparison: true,
  },
  {
    id: 'prod-3',
    name: 'LED Desk Lamp',
    sku: 'LL-302',
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=300&auto=format&fit=crop&q=80',
    costPrice: 8.50,
    shippingCost: 2.00,
    packagingCost: 1.00,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 3.50,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 24.99,
    createdAt: '2024-05-15',
    updatedAt: '2024-05-15',
    status: 'good',
    bestFor: 'Good Potential',
    notes: 'Increase price by $2 to enter 36%+ margin tier.',
    inComparison: true,
  },
  {
    id: 'prod-4',
    name: 'Silicone Phone Case',
    sku: 'PC-889',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=300&auto=format&fit=crop&q=80',
    costPrice: 6.00,
    shippingCost: 2.00,
    packagingCost: 1.00,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 3.00,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 15.99,
    createdAt: '2024-05-12',
    updatedAt: '2024-05-12',
    status: 'low',
    bestFor: 'Needs Work',
    notes: 'Low profit margin due to ad costs. Bundle or increase price.',
    inComparison: true,
  },
  {
    id: 'prod-5',
    name: 'Bluetooth Earbuds ANC',
    sku: 'BE-201',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=300&auto=format&fit=crop&q=80',
    costPrice: 18.00,
    shippingCost: 2.00,
    packagingCost: 1.00,
    otherProductCost: 1.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 7.00,
    creatorCost: 0.50,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 39.99,
    createdAt: '2024-05-10',
    updatedAt: '2024-05-10',
    status: 'low',
    bestFor: 'Volume Play',
    notes: 'High ad CAC is compressing net profit to $5.40.',
    inComparison: false,
  },
  {
    id: 'prod-6',
    name: 'Sunset Projection Lamp',
    sku: 'SPL-550',
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=300&auto=format&fit=crop&q=80',
    costPrice: 5.50,
    shippingCost: 2.20,
    packagingCost: 0.80,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 2.50,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 22.99,
    createdAt: '2024-05-08',
    updatedAt: '2024-05-08',
    status: 'excellent',
    bestFor: 'High Margin',
    notes: 'Very high profit margin with organic TikTok virality.',
    inComparison: false,
  }
];

export const STORE_1_LISTINGS: ListingItem[] = [
  {
    id: 'list-1',
    productId: 'prod-1',
    productName: 'Fast Wireless Charging Pad 15W Qi-Certified',
    sku: 'WC-001',
    sellingPrice: 29.99,
    costPrice: 9.00,
    expectedProfit: 12.99,
    expectedMargin: 43.3,
    category: 'Cell Phones & Accessories > Wireless Chargers',
    description: 'Ultra-thin fast wireless charging pad with intelligent temperature control. Compatible with iPhone and Samsung Galaxy.',
    keyFeatures: ['15W Fast Charge technology', 'Case friendly up to 5mm', 'Sleep-friendly LED indicator', 'Anti-slip silicone design'],
    tags: ['#wirelesscharger', '#techgadgets', '#tiktokmademebuyit', '#desksetup'],
    status: 'synced',
    createdAt: '2024-05-18',
  },
  {
    id: 'list-2',
    productId: 'prod-2',
    productName: 'Fitness Smart Watch with Heart Rate & SpO2 Monitor',
    sku: 'SW-104',
    sellingPrice: 49.99,
    costPrice: 18.00,
    expectedProfit: 18.50,
    expectedMargin: 37.0,
    category: 'Wearable Technology > Smart Watches',
    description: 'All-day activity tracking with 1.8" HD touchscreen, IP68 waterproof rating, and 7-day battery life.',
    keyFeatures: ['1.8" Full Touch Screen', '100+ Sports Modes', 'IP68 Waterproof', '7-Day Long Battery Life'],
    tags: ['#smartwatch', '#fitnessgoals', '#healthtracker', '#techfinds'],
    status: 'ready',
    createdAt: '2024-05-16',
  }
];

export const STORE_1_ORDERS: OrderEconomics[] = [
  {
    id: 'TT-984210',
    product: 'Wireless Charger Fast 15W',
    customer: 'Sarah Jenkins',
    date: 'Today, 2:45 PM',
    sellingPrice: 29.99,
    productCost: 9.00,
    shippingAndPkg: 3.00,
    tiktokFees: 5.10,
    adCPA: 3.50,
    netProfit: 9.39,
    margin: 31.3,
    status: 'Shipped',
  },
  {
    id: 'TT-984209',
    product: 'Fitness Smart Watch Pro',
    customer: 'Marcus Vance',
    date: 'Today, 1:12 PM',
    sellingPrice: 49.99,
    productCost: 18.00,
    shippingAndPkg: 3.50,
    tiktokFees: 8.50,
    adCPA: 5.00,
    netProfit: 14.99,
    margin: 30.0,
    status: 'Processing',
  },
  {
    id: 'TT-984208',
    product: 'LED Desk Lamp',
    customer: 'Emily Watson',
    date: 'Yesterday',
    sellingPrice: 24.99,
    productCost: 8.50,
    shippingAndPkg: 3.00,
    tiktokFees: 4.25,
    adCPA: 3.50,
    netProfit: 5.74,
    margin: 23.0,
    status: 'Delivered',
  },
  {
    id: 'TT-984207',
    product: 'Wireless Charger Fast 15W',
    customer: 'David Miller',
    date: 'Yesterday',
    sellingPrice: 29.99,
    productCost: 9.00,
    shippingAndPkg: 3.00,
    tiktokFees: 5.10,
    adCPA: 0.00,
    netProfit: 12.89,
    margin: 43.0,
    status: 'Delivered',
  }
];

export const STORE_1_MONTHLY: MonthlyDataPoint[] = [
  { month: 'Nov', profit: 4800, revenue: 14200, margin: 33.8, peak: false },
  { month: 'Dec', profit: 7200, revenue: 21800, margin: 33.0, peak: false },
  { month: 'Jan', profit: 6400, revenue: 19500, margin: 32.8, peak: false },
  { month: 'Feb', profit: 9100, revenue: 27300, margin: 33.3, peak: false },
  { month: 'Mar', profit: 8600, revenue: 25400, margin: 33.8, peak: false },
  { month: 'Apr', profit: 11400, revenue: 33600, margin: 33.9, peak: false },
  { month: 'May', profit: 12540, revenue: 36660, margin: 34.2, peak: true },
];

// ----------------------------------------------------
// STORE 2: TrendVibe US (Main) (Viral Beauty & Apparel - US)
// ----------------------------------------------------
export const STORE_2_PRODUCTS: ProductItem[] = [
  {
    id: 'tv-1',
    name: 'Heatless Hair Silk Curler Set',
    sku: 'TV-HHC-01',
    category: 'Beauty & Personal Care',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300&auto=format&fit=crop&q=80',
    costPrice: 4.20,
    shippingCost: 2.10,
    packagingCost: 0.80,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 8.00,
    tiktokAdsCost: 3.00,
    creatorCost: 0.50,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 24.99,
    createdAt: '2024-05-20',
    updatedAt: '2024-05-20',
    status: 'excellent',
    bestFor: 'Viral Sensation 🔥',
    notes: 'Massive organic TikTok UGC volume. Over 2.4k units sold this week.',
    inComparison: true,
  },
  {
    id: 'tv-2',
    name: 'HydraGlow Lip Plumping Oil',
    sku: 'TV-LPO-09',
    category: 'Beauty & Personal Care',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&auto=format&fit=crop&q=80',
    costPrice: 2.90,
    shippingCost: 1.80,
    packagingCost: 0.60,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 10.00,
    tiktokAdsCost: 2.50,
    creatorCost: 0.30,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 18.99,
    createdAt: '2024-05-19',
    updatedAt: '2024-05-19',
    status: 'excellent',
    bestFor: 'High Profit Margin',
    notes: '51% net margin with high re-order rates.',
    inComparison: true,
  },
  {
    id: 'tv-3',
    name: 'Seamless Sculpt Hourglass Bodysuit',
    sku: 'TV-BOD-44',
    category: 'Apparel & Shapewear',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=300&auto=format&fit=crop&q=80',
    costPrice: 8.50,
    shippingCost: 2.80,
    packagingCost: 1.00,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 7.00,
    tiktokAdsCost: 4.80,
    creatorCost: 0.50,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 34.99,
    createdAt: '2024-05-18',
    updatedAt: '2024-05-18',
    status: 'good',
    bestFor: 'Volume Winner',
    notes: 'High conversion rate on TikTok Spark ads.',
    inComparison: true,
  },
  {
    id: 'tv-4',
    name: 'Stainless Steel Cryo Ice Roller',
    sku: 'TV-ICR-12',
    category: 'Beauty Tools',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=300&auto=format&fit=crop&q=80',
    costPrice: 3.10,
    shippingCost: 2.00,
    packagingCost: 0.70,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 6.00,
    tiktokAdsCost: 2.20,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 16.99,
    createdAt: '2024-05-15',
    updatedAt: '2024-05-15',
    status: 'excellent',
    bestFor: 'Great Upsell',
    notes: 'Pairs great with lip oil bundles.',
    inComparison: false,
  },
  {
    id: 'tv-5',
    name: 'Cloud Soft Unisex Slides',
    sku: 'TV-SLD-88',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=300&auto=format&fit=crop&q=80',
    costPrice: 5.80,
    shippingCost: 3.20,
    packagingCost: 1.20,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 10.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 3.50,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 22.99,
    createdAt: '2024-05-10',
    updatedAt: '2024-05-10',
    status: 'good',
    bestFor: 'Consistent Performer',
    notes: 'Steady everyday volume seller.',
    inComparison: false,
  }
];

export const STORE_2_LISTINGS: ListingItem[] = [
  {
    id: 'tv-list-1',
    productId: 'tv-1',
    productName: 'Heatless Hair Silk Curler Kit No Heat Overnight Curls',
    sku: 'TV-HHC-01',
    sellingPrice: 24.99,
    costPrice: 4.20,
    expectedProfit: 12.89,
    expectedMargin: 51.6,
    category: 'Beauty > Hair Care > Styling Tools',
    description: 'Get salon-quality bouncy curls with zero heat damage. 100% pure satin silk material suitable for all hair types.',
    keyFeatures: ['100% Mulberry Satin Silk', 'Includes claw clip and scrunchies', 'Zero heat damage', 'Comfortable overnight design'],
    tags: ['#heatlesscurls', '#beautytok', '#hairtutorial', '#tiktokviral'],
    status: 'synced',
    createdAt: '2024-05-20',
  },
  {
    id: 'tv-list-2',
    productId: 'tv-2',
    productName: 'HydraGlow Peptide & Berry Plumping Lip Oil',
    sku: 'TV-LPO-09',
    sellingPrice: 18.99,
    costPrice: 2.90,
    expectedProfit: 9.71,
    expectedMargin: 51.1,
    category: 'Beauty > Makeup > Lip Gloss',
    description: 'Ultra-nourishing tinted lip oil enriched with hyaluronic acid and vitamin E for juicy, glassy shine.',
    keyFeatures: ['Non-sticky mirror finish', 'Hydrating hyaluronic acid', 'Subtle berry tint', 'Jumbo applicator wand'],
    tags: ['#lipoil', '#glossylips', '#cleangirl', '#beautyfinds'],
    status: 'ready',
    createdAt: '2024-05-19',
  }
];

export const STORE_2_ORDERS: OrderEconomics[] = [
  {
    id: 'TV-772101',
    product: 'Heatless Hair Silk Curler Set',
    customer: 'Chloe Bennett',
    date: 'Today, 3:10 PM',
    sellingPrice: 24.99,
    productCost: 4.20,
    shippingAndPkg: 2.90,
    tiktokFees: 5.00,
    adCPA: 3.00,
    netProfit: 9.89,
    margin: 39.6,
    status: 'Shipped',
  },
  {
    id: 'TV-772100',
    product: 'HydraGlow Lip Plumping Oil',
    customer: 'Maya Lin',
    date: 'Today, 1:40 PM',
    sellingPrice: 18.99,
    productCost: 2.90,
    shippingAndPkg: 2.40,
    tiktokFees: 4.18,
    adCPA: 0.00,
    netProfit: 9.51,
    margin: 50.1,
    status: 'Processing',
  },
  {
    id: 'TV-772099',
    product: 'Seamless Sculpt Bodysuit',
    customer: 'Jessica Taylor',
    date: 'Yesterday',
    sellingPrice: 34.99,
    productCost: 8.50,
    shippingAndPkg: 3.80,
    tiktokFees: 6.65,
    adCPA: 4.80,
    netProfit: 11.24,
    margin: 32.1,
    status: 'Delivered',
  }
];

export const STORE_2_MONTHLY: MonthlyDataPoint[] = [
  { month: 'Nov', profit: 7400, revenue: 21500, margin: 34.4, peak: false },
  { month: 'Dec', profit: 11200, revenue: 32400, margin: 34.6, peak: false },
  { month: 'Jan', profit: 9800, revenue: 28100, margin: 34.9, peak: false },
  { month: 'Feb', profit: 13600, revenue: 38200, margin: 35.6, peak: false },
  { month: 'Mar', profit: 15400, revenue: 43100, margin: 35.7, peak: false },
  { month: 'Apr', profit: 17200, revenue: 47900, margin: 35.9, peak: false },
  { month: 'May', profit: 18920, revenue: 52400, margin: 36.1, peak: true },
];

// ----------------------------------------------------
// STORE 3: QuickGlow UK Store (UK Home & Gadgets - GBP £)
// ----------------------------------------------------
export const STORE_3_PRODUCTS: ProductItem[] = [
  {
    id: 'qg-1',
    name: 'Flame Ultrasonic Aroma Diffuser',
    sku: 'QG-DIF-01',
    category: 'Home & Fragrance',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=300&auto=format&fit=crop&q=80',
    costPrice: 7.50,
    shippingCost: 2.20,
    packagingCost: 0.80,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 9.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 3.20,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 28.99,
    createdAt: '2024-05-17',
    updatedAt: '2024-05-17',
    status: 'excellent',
    bestFor: 'UK Top Seller 🇬🇧',
    notes: 'Realistic flame effect with essential oils. High viral aesthetic in UK interior decor niche.',
    inComparison: true,
  },
  {
    id: 'qg-2',
    name: 'Electric Lint & Bobble Remover Pro',
    sku: 'QG-LNT-05',
    category: 'Home & Laundry',
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=300&auto=format&fit=crop&q=80',
    costPrice: 4.20,
    shippingCost: 1.80,
    packagingCost: 0.60,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 9.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 2.00,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 16.99,
    createdAt: '2024-05-15',
    updatedAt: '2024-05-15',
    status: 'excellent',
    bestFor: 'High Profit Margin',
    notes: 'Outstanding unit economics with 46% net profit.',
    inComparison: true,
  },
  {
    id: 'qg-3',
    name: 'RGB Mechanical Gaming Keyboard',
    sku: 'QG-KB-22',
    category: 'Computers & Gaming',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
    costPrice: 14.00,
    shippingCost: 2.90,
    packagingCost: 1.10,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 9.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 4.50,
    creatorCost: 0.50,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 39.99,
    createdAt: '2024-05-12',
    updatedAt: '2024-05-12',
    status: 'good',
    bestFor: 'High Value Item',
    notes: 'Solid gamer market appeal in UK TikTok feeds.',
    inComparison: true,
  },
  {
    id: 'qg-4',
    name: 'Reusable Silicone Air Fryer Liners (Pack of 2)',
    sku: 'QG-AFL-08',
    category: 'Kitchenware',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=300&auto=format&fit=crop&q=80',
    costPrice: 2.50,
    shippingCost: 1.60,
    packagingCost: 0.50,
    otherProductCost: 0.00,
    tiktokCommissionPercent: 9.00,
    transactionFeePercent: 2.00,
    affiliatePercent: 5.00,
    tiktokAdsCost: 1.50,
    creatorCost: 0.00,
    otherMarketingCost: 0.00,
    customExpenses: 0.00,
    sellingPrice: 12.99,
    createdAt: '2024-05-09',
    updatedAt: '2024-05-09',
    status: 'excellent',
    bestFor: 'Kitchen Essential',
    notes: 'Very high volume kitchen gadget.',
    inComparison: false,
  }
];

export const STORE_3_LISTINGS: ListingItem[] = [
  {
    id: 'qg-list-1',
    productId: 'qg-1',
    productName: 'Flame Essential Oil Aroma Diffuser with Ambient LED',
    sku: 'QG-DIF-01',
    sellingPrice: 28.99,
    costPrice: 7.50,
    expectedProfit: 13.85,
    expectedMargin: 47.8,
    category: 'Home & Kitchen > Home Fragrance > Diffusers',
    description: 'Realistic fireplace flame simulation with ultra-fine aromatherapy mist. Auto shut-off safety sensor and whisper quiet operation.',
    keyFeatures: ['Realistic 3D flame effect', 'Auto waterless shutoff', 'Ultra quiet <25dB', 'USB Type-C powered'],
    tags: ['#diffuser', '#cozyhome', '#ukdeals', '#tiktokmademebuyituk'],
    status: 'synced',
    createdAt: '2024-05-17',
  }
];

export const STORE_3_ORDERS: OrderEconomics[] = [
  {
    id: 'UK-665120',
    product: 'Flame Aroma Diffuser',
    customer: 'Oliver Davies',
    date: 'Today, 4:20 PM',
    sellingPrice: 28.99,
    productCost: 7.50,
    shippingAndPkg: 3.00,
    tiktokFees: 4.64,
    adCPA: 3.20,
    netProfit: 10.65,
    margin: 36.7,
    status: 'Shipped',
  },
  {
    id: 'UK-665119',
    product: 'Electric Bobble Remover',
    customer: 'Charlotte Smith',
    date: 'Today, 2:05 PM',
    sellingPrice: 16.99,
    productCost: 4.20,
    shippingAndPkg: 2.40,
    tiktokFees: 2.72,
    adCPA: 2.00,
    netProfit: 5.67,
    margin: 33.4,
    status: 'Processing',
  }
];

export const STORE_3_MONTHLY: MonthlyDataPoint[] = [
  { month: 'Nov', profit: 3900, revenue: 11800, margin: 33.0, peak: false },
  { month: 'Dec', profit: 5800, revenue: 17200, margin: 33.7, peak: false },
  { month: 'Jan', profit: 5100, revenue: 15300, margin: 33.3, peak: false },
  { month: 'Feb', profit: 6900, revenue: 20400, margin: 33.8, peak: false },
  { month: 'Mar', profit: 7400, revenue: 21900, margin: 33.8, peak: false },
  { month: 'Apr', profit: 8600, revenue: 25400, margin: 33.9, peak: false },
  { month: 'May', profit: 9450, revenue: 27800, margin: 34.0, peak: true },
];

// ----------------------------------------------------
// DEFAULT INITIAL STORES COLLECTION
// ----------------------------------------------------
export const INITIAL_STORES: StoreInfo[] = [
  {
    id: 'store-1',
    name: 'My TikTok Shop',
    handle: '@mytiktokshop_official',
    region: 'US',
    currency: 'USD',
    currencySymbol: '$',
    settings: {
      ...DEFAULT_SETTINGS,
      storeName: 'My TikTok Shop',
      storeHandle: '@mytiktokshop_official',
      currency: 'USD',
      currencySymbol: '$',
      tiktokCommissionPercent: 10.0,
      defaultShippingCost: 2.0,
      defaultPackagingCost: 1.0,
    },
    products: STORE_1_PRODUCTS,
    listings: STORE_1_LISTINGS,
    orders: STORE_1_ORDERS,
    monthlyData: STORE_1_MONTHLY,
  },
  {
    id: 'store-2',
    name: 'TrendVibe US (Main)',
    handle: '@trendvibe_us',
    region: 'US',
    currency: 'USD',
    currencySymbol: '$',
    settings: {
      ...DEFAULT_SETTINGS,
      storeName: 'TrendVibe US (Main)',
      storeHandle: '@trendvibe_us',
      currency: 'USD',
      currencySymbol: '$',
      tiktokCommissionPercent: 10.0,
      defaultShippingCost: 2.5,
      defaultPackagingCost: 0.9,
      targetProfitMarginPercent: 40.0,
    },
    products: STORE_2_PRODUCTS,
    listings: STORE_2_LISTINGS,
    orders: STORE_2_ORDERS,
    monthlyData: STORE_2_MONTHLY,
  },
  {
    id: 'store-3',
    name: 'QuickGlow UK Store',
    handle: '@quickglow_uk',
    region: 'UK',
    currency: 'GBP',
    currencySymbol: '£',
    settings: {
      ...DEFAULT_SETTINGS,
      storeName: 'QuickGlow UK Store',
      storeHandle: '@quickglow_uk',
      currency: 'GBP',
      currencySymbol: '£',
      tiktokCommissionPercent: 9.0,
      defaultShippingCost: 2.2,
      defaultPackagingCost: 0.8,
      targetProfitMarginPercent: 35.0,
    },
    products: STORE_3_PRODUCTS,
    listings: STORE_3_LISTINGS,
    orders: STORE_3_ORDERS,
    monthlyData: STORE_3_MONTHLY,
  }
];

// Backwards compatibility aliases
export const INITIAL_PRODUCTS = STORE_1_PRODUCTS;
export const INITIAL_LISTINGS = STORE_1_LISTINGS;
export const MONTHLY_OVERVIEW_DATA = STORE_1_MONTHLY;

